# Generated by Django 4.1.3 on 2022-12-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_alter_newsstory_options_newsstory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
