# Generated by Django 4.1.3 on 2022-12-16 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0008_alter_category_options_alter_newsstory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
